### ISSUE TITLE
Non existing add apps should be disabled or not visible

### ISSUE THREAD

**Issue by margorski** [margorski/exodos-launcher#26]
Add apps are combination of entries from xml and physical files. Because of that in exodos v6 it is common that AddApp manual is shown even if PDF doesn't exist physically on the drive (the manual addon was not installed). 

In that case that entry should be 
a) disabled, grayed out
or
b) not shown at all

**Comment by parricc** [comment]
This issue seems to be resolved with the most recent build.

**Comment by margorski** [comment]
Fixed with last changes.

**Comment by margorski** [comment]
The non existing extras (existing in xml but not in the disk) are filtered out.
