### ISSUE TITLE
Additional resources not visible

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#29]
In the most recent build I've done of exogui, based on the current state of the repo (2024-07-30), most additional resources are not visible. The only one that appears is `Manual`, which is defined separately from the other additional resources.

The manual location for each game is defined in the platforms xml file by `<ManualPath>` entry.
In eXo collections, manuals are typically put in the `Manuals/<Platform>` directory. 

Other additional resources are located in subdirectories of the `RootFolder` entry in the appropriate `Platforms/Data/` xml file.
**All subdirectories of the `RootFolder` entry should be searched for additional resources.**

See this comparison between a build based on the current contents of the repo versus one I compiled on 2024-06-05:
![missing additional resources](https://github.com/user-attachments/assets/68a67c26-0f86-4e1e-9f1b-df6776a527e7)

The older build included items in the `Extras` folder. However, even it was missing some additional resources as there were also assets in a `Magazines` subdirectory.

For the game in the example screenshot, the `MS-DOS.xml` file has the following line:
`<RootFolder>eXo\eXoDOS\!dos\dott</RootFolder>`

In this example, the above directory contains the following subdirectories and files:

```
── Extras
│   ├── Alternate Launcher.bat
│   ├── Alternate Launcher.bsh
│   ├── Alternate Launcher.command
│   ├── Day of the Tentacle (Non-Playable Demo Trailer).mp4
│   ├── Day of the Tentacle - Trailer.mp4
│   ├── Game Design Document.pdf
│   ├── Hint Book.pdf
│   ├── Reference Card.pdf
│   ├── Restored Artwork by Laserschwert - Box.jpg
│   ├── Restored Artwork by Laserschwert - Box (No Text).jpg
│   ├── Restored Artwork by Laserschwert - Box (No Title).jpg
│   └── VG Maps.pdf
└── Magazines
    ├── Walkthrough PC Gamer 1995-12 page 321.bat
    ├── Walkthrough PC Gamer 1995-12 page 321.bsh
    └── Walkthrough PC Gamer 1995-12 page 321.command
```

So in the 2024-06-05 build, we were missing an entry that pointing to the `Walkthrough PC Gamer 1995-12 page 321.command` script, which would have shown a walkthrough from a magazine.

But in the current build, nothing is showing from any of these subdirectories.

**Comment by parricc** [comment]
So, looking into other files, it's not all subdirectories in all cases.

For example, in `MS-DOS Magazines & Newsletters.xml`, there are some entries for interactive discs. One example has the following RootFolder tag:

`<RootFolder>eXo\Magazines\PCGamerUS\PCGamer_1997_01</RootFolder>`

If we look in that directory, it has stuff we wouldn't want listed in a frontend:

```
├── Apps
│   ├── qt
│   │   ├── NPQTW16.DLL
│   │   ├── PROBS16.TXT
│   │   ├── QTINSTAL.EXE
│   │   ├── QTVRW.QTC
│   │   └── README16.TXT
│   ├── VFW
│   │   ├── ACMCMPRS.DL_
│   │   ├── AVICAP.DL_
│   │   ├── AVIFILE.DL_
│   │   ├── CLEANUP.RE_
│   │   ├── COMPOBJ.DL_
│   │   ├── COPYRITE.TXT
│   │   ├── CTL3D.DL_
│   │   ├── DISPDIB.DL_
│   │   ├── DVA.38_
│   │   ├── ICCVID.DR_
│   │   ├── IMAADPCM.AC_
│   │   ├── INIUPD.DL_
│   │   ├── IR32.DL_
│   │   ├── IR41.DL_
│   │   ├── IYVU9.DL_
│   │   ├── MAP_WIN.HL_
│   ├── w32s
│   │   ├── 32SINST.INF
│   │   ├── 32SINST.MST
│   │   ├── CARDS.DLL
│   │   ├── COMCTL32.DLL
│   │   ├── COMDLG32.DLL
│   │   ├── COMPOBJ.DLL
│   │   ├── CRTDLL.DLL
│   │   ├── CTYPE.NLS
│   │   ├── FREECELL.EXE
│   │   ├── FREECELL.HLP
│   └── wing
├── cd
│   └── pcgamer.iso
├── drivers
│   ├── s3
│   │   ├── 8514FIX.FO_
│   │   ├── 8514OEM.FO_
│   │   ├── 8514SYS.FO_
```

The above is a partial list to give a general idea.

I haven't really dug into how LaunchBox works, so I don't know where the distinction is made between what should and shouldn't be listed.

**Comment by margorski** [comment]
Partially fixed in the commit: 95e9e8c7f70ed9beb41a71e7b74f960bd39fec43

Now extras from the extras directory are properly loaded on the exogui initialization.

**Comment by parricc** [comment]
Perhaps hard-coding a `Magazines` subdirectory of RootFolder in the same way as the `Extras` subdirectory will be the best way to get the shell scripts that launch magazine references displayed.

**Comment by parricc** [comment]
This issue is resolved. The refresh issue is still present, but in another ticket.
