### ISSUE TITLE
MS-DOS Magazines & Newsletters.xml not parsing correctly

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#32]
The `Data/Platforms/MS-DOS Magazines & Newsletters.xml` file is not showing up as a tab in exogui.

Edit: I suspected this was due to the `&` character in its filename. However, after editing the xml files and renaming it to simply `MS-DOS Magazines.xml`, the tab still was not showing up. So it would appear the root of the issue is something else.

**Comment by parricc** [comment]
After doing some testing by editing the xml files, it appears to be something that's not actually `&` character.

**Comment by margorski** [comment]
Actually that was the ampersand. Fixed in the 90c3eacae7a5e52e2eb7efba65c4aa6a52a1e7ca
