### ISSUE TITLE
broken media for files containing # character

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#34]
`HyperComix issue #1 - Lance Stone: Trouble at the Woz` has broken media:
- 30 Second Demo
- Box - Front
- Screenshot - Game Title
- Screenshot - Gameplay

Path to media files for the above:
```
Videos/MS-DOS/HyperComix issue # 1 - Lance Stone - Trouble at the Woz (1993).mp4
Images/MS-DOS/Box - Front/HyperComix issue #1 - Lance Stone_ Trouble at the Woz-00.jpg
Images/MS-DOS/Screenshot - Game Title/HyperComix issue #1 - Lance Stone_ Trouble at the Woz-02.png
Images/MS-DOS/Screenshot - Gameplay/HyperComix issue #1 - Lance Stone_ Trouble at the Woz-02.png
```

See attached screenshot:
![exogui - broken media](https://github.com/user-attachments/assets/f1eed567-2ee9-437f-9cba-7a8491a60cae)

**Comment by parricc** [comment]
This issue is almost certainly due to # character being present in the filenames.

**Comment by colin969** [comment]
Fixed by https://github.com/margorski/exodos-launcher/commit/11b9478794d959cd0dfce54039033f8d706b2f3a
