### ISSUE TITLE
Extras and images/videos are not refreshed after installing game.

### ISSUE THREAD

**Issue by margorski** [margorski/exodos-launcher#35]
Extras and videos are downloaded with the game on the game install (for the exodos lite). The extras and videos needs to be refreshed after installing game .

**Comment by parricc** [comment]
This issue also affects the installation status of a game. After installing a game, the right hand pane will still say "Install" with "Setup" greyed out until restarting eXoGUI. The inverse equivalent happens if uninstalling a game.

**Comment by parricc** [comment]
I should note on the above. If you have a game selected and install it, the right hand pane will reflect that until you click off of it and then click back on.

**Comment by parricc** [comment]
My last comment is no longer valid with the most recent build. The game no longer shows as installed after installing even if the game selected does not change.

**Comment by parricc** [comment]
With the most recent build, games correctly update the install status in the right-hand pane.. And the videos will show up after installing a game in the lite version as well.

However, the Extras still do not show up for people that install a game in the lite version until restarting exogui.

**Comment by margorski** [comment]
Fixed. Leaving task open upon further tests. Not all of the file extension for the extras are whitelisted yet so some of the stuff may still do not appear (will be done as part of the other task) but most of them should appear and works.

**Comment by parricc** [comment]
Tested on a few games in lite, and the Extras still do not show up until restarting exogui.

A few items also do not appear even after a restart, but I assume that's due to them not being whitelisted.

**Comment by parricc** [comment]
Tested on the most recent build, and the refresh is now working as expected.

Only one minor issue - for some games, the video refreshes before it finishes getting unzipped, which results in the preview not playing until you click on a different image and back again. Not a huge deal, but a slight delay between the detection of the file and the adding of the video preview might help with that.

**Comment by margorski** [comment]
Added 3 seconds' delay. That of course won't always work. This depends on the video size and disk speed. But I think in 95% of cases it will do the work. Not much we could do in that matter.

**Comment by margorski** [comment]
REduced to 2 seconds.
