### ISSUE TITLE
exogui fails to launch when ipv6 is disabled

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#38]
A tester, Sämbyl,  has reported that exogui is failing to launch on a Debian trixie unstable (trixie/sid) computer that is using x11 and KDE.

```
Distributor ID: Debian
Description:    Debian GNU/Linux trixie/sid
Release:        n/a
Codename:       trixie
Linux OjiDeb 6.10.3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.3-1 (2024-08-04) x86_64 GNU/Linux
```

[exogui.error.20240817.txt](https://github.com/user-attachments/files/16644724/exogui.error.20240817.txt)
[lddexogui.txt](https://github.com/user-attachments/files/16644765/lddexogui.txt)

**Comment by parricc** [comment]
Notable output from the error involving the ports:

[...]
`Starting file server with 12101 - 12200 port.`
[...]
Started file server on port 12101
[...]
Error: connect ECONNREFUSED 127.0.0.1:12001
[...]

It seems it's starting a server on port 12101, but then listening on 12001 instead.

**Comment by parricc** [comment]
This issue happens with both the AppImage and native binary.

**Comment by parricc** [comment]
Sämbyl used netstat to determine that exogui was listening on ipv6:
```
tcp6       0      0 ::1:12101               :::*                    LISTEN      11361/exogui
tcp6       0      0 ::1:12001               :::*                    LISTEN      11361/exogui
```

He had ipv6 disabled. After enabling ipv6 on eth0, exogui successfully started.

**Comment by colin969** [comment]
Fixed by https://github.com/margorski/exodos-launcher/commit/f90113c7f211c8e0b611941fe358c14a4bfa960c
