### ISSUE TITLE
Doubled up category tabs on the top of the screen.

### ISSUE THREAD

**Issue by alphagold3** [margorski/exodos-launcher#40]
I just recently installed exoDos on Linux and after installing and running exogui it's showing doubled up tabs for all the different categories except ScummVM and ScummVM SVN. I've only got 1 copy of each XML file in the eXo/Data/Platforms folder so I'm not sure what's going on.
![image](https://github.com/user-attachments/assets/7efa64ac-8b6d-4d18-b991-e2f8033878e4)
![image](https://github.com/user-attachments/assets/991ae587-cecf-4f95-b105-5273bb40d0ba)

**Comment by parricc** [comment]
This is not an exogui issue. Your xml files are not correct.

**Comment by alphagold3** [comment]
Yes. I tested it and this seems to be working now. It seems it was an issue with how I installed exoDos.
