### ISSUE TITLE
Some items in the list are hidden by the filters and the bottom bar.

### ISSUE THREAD

**Issue by alphagold3** [margorski/exodos-launcher#41]
When I first launched eXoGUI the filters defaulted to be open. I was scrolling through the list and noticed that some weird white stuff at the bottom of the list that looks like the top pixels of text. I discovered I could click on it and it is an actual game hidden by the UI. If I hide the filters then it reveals more of these hidden items but the last few are still hidden. If I view it as a grid with the filters open then I can still see half of the images on the bottom row but can't see the names of the games. If I hide the filters then I can see the entirety of the images on the bottom row but still can't see the names.
![image](https://github.com/user-attachments/assets/db7ee3c7-550c-4bdb-968d-127bca469a8e)
![image](https://github.com/user-attachments/assets/d757b02d-aa30-435b-af17-79cf7f59b45f)
![image](https://github.com/user-attachments/assets/a05fbfb0-625d-4d24-a5b5-82f8700ebd42)
![image](https://github.com/user-attachments/assets/70ef4552-0e3e-41be-ba9b-3b0b03a16a1f)

**Comment by parricc** [comment]
Confirmed that the window is hiding the bottom items.
![exogui-hiddenlastgames](https://github.com/user-attachments/assets/36be2e97-9298-410c-abee-eb851fc579e2)
For me, Zyll is the last thing in the list you can see, whether the window is maximized or small.
If you select that game in the list, and press the down arrow, there is also the following games that go beyond what is visible in the window.

ZZT
ZZT: eXoZZT
ZZT's City
ZZT's Revenge!
µLabyrinth

The scrollbar indicator for where you are completely goes off-screen when you go past "Trick or Treat." It would seem the pane sizing needs to be readjusted. This possibly became a problem after the filter buttons got added at the top, offsetting the list slightly from where it used to be.

**Comment by colin969** [comment]
I encountered the same issue in Flashpoint implementing it there. I did fix it, but I'll have to check the styles to see what I changed.

**Comment by colin969** [comment]
Fixed by https://github.com/margorski/exodos-launcher/commit/25d4b2f625e9f18b37ffb7c35ea97c66f84b7f29
