### ISSUE TITLE
Most of the games are displaying doubled up in the UI

### ISSUE THREAD

**Issue by alphagold3** [margorski/exodos-launcher#42]
Most of the games are displaying as doubled up in the UI. Selecting one will highlight both of the entries for that game.
![image](https://github.com/user-attachments/assets/8d79cfb1-1418-40a8-977b-c6f6874abc4d)
![image](https://github.com/user-attachments/assets/95017ff7-2d53-4255-8161-840e7fc0aa97)

**Comment by parricc** [comment]
This is not an exogui issue. Your xml files are not correct.

**Comment by alphagold3** [comment]
Yes. I tested some stuff and I made a mistake in the install. It seems to be working now.
