### ISSUE TITLE
add a cooldown timer after pressing buttons

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#45]
We should have a short period of time before a button can be repressed, maybe 3 seconds. It's too easy to accidentally press something like `Install` multiple times on the Steam Deck. This will prevent multiple windows from getting launched at the same time if that happens.

**Comment by colin969** [comment]
Fixed by https://github.com/margorski/exodos-launcher/commit/8731739d39e5b0e396f291203c3b97d0a897fcc3
