### ISSUE TITLE
add welcome page

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#46]
It would be good to have a collection agnostic "exogui" welcome page with buttons to open the following in the root directory of the collection: 
- install_dependencies.command
- any txt files
- any pdf files

**Comment by margorski** [comment]
Really we want that? Maybe we should ask users? 
Me as an extensive user of the exogui never really used the welcome page. It was immediate switch to the games list. And the welcome page with the news really easy get out of sync and get stale. And for the scripts, cmon, we are linux users, we start installing the package from the console, why would anyone go to the app to run the script?

The only thing I would like the welcome page for is if we would get recently played games section (but it is not implemented yet and wouldn't be easy) and  random games proposition (that would be easy though).

let's discuss that with the users

**Comment by parricc** [comment]
We can redefine what a "welcome page" means. It doesn't have to be the default page on launch, but there is a lot of value in a tab having a tab with the buttons I described. 

A lot of people will presumably be launching from a desktop or application menu shortcut. Or from gaming mode on the Steam Deck. People may need to periodically run the install dependencies script. For example, if you update video drivers, that may break OpenGL in the flatpaks until flatpak update has been run. Then there's value in easy access to the txt and PDF files from the frontend.

A news section is less important. This could look more like a simple about page. It might say exogui with the version number. There could be a list of frontend contributors, and a link to the repository. If you want to have a way to update exogui from exogui itself, this would be the page to put that on. Then buttons to launch the dependency installer and any txt or pdf files in the root directory of the collection.

**Comment by margorski** [comment]
You got the point. I will think where to put that.

**Comment by margorski** [comment]
I implemented the menu with the automatically added exodos resources and the about page.

The resources are dynamically loaded. The .txt, .pdf and .command files (excluding exogui.command and exodreamm.command files). The files are added to the Documents and Scripts submenu.

The code may be easily modified by adding/changing entries in the:
`ExodosResourcesTypeExtensions (src/renderer/util/exoResources.ts:5)`
and 
filtered files in the `(src/renderer/util/exoResources.ts:7)`
