### ISSUE TITLE
widen default desktop window size

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#49]
The default desktop window size before manually resizing cuts off the right-hand pane. It should be widened so that the entire pane is visible. See screenshot:
![exogui-defaultdesktopwindowsize](https://github.com/user-attachments/assets/dead0491-7bb0-4937-854e-b625d907c61f)

**Comment by margorski** [comment]
Changed the default value for the maximized parameter to true so exogui on first run will start maximized what would solve that problem.
