### ISSUE TITLE
Add option to open game config directory

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#51]
Having an option to open the game config directory in a file manager from the frontend would be ideal. This was emphasized in Get Off My Lawn's review of the eXoDOS 5 Linux patch. He named the lack of this feature his biggest complaint. And it's understandable that people would like a way to quickly get to the conf file for a game.

The directory containing a game's conf file is defined by the `<RootFolder>` value in the xml file. However, a few of the `<RootFolder>` values are inaccurate, and eXo doesn't consider then a high priority to fix. If we want to use a path that is guaranteed to be 100% accurate for any given game, the shell file defined by `<ApplicationPath>` will always be located in the same directory as the game's conf file.

**Comment by colin969** [comment]
Added in https://github.com/margorski/exodos-launcher/commit/394593c5d86c2669fc07fed5d29cd22bb52d3317

![image](https://github.com/user-attachments/assets/bd8c3012-7c5f-4d33-90e4-cac153caa9d6)
