### ISSUE TITLE
leading 0 characters should not be stripped from shell script parameters

### ISSUE THREAD

**Issue by parricc** [margorski/exodos-launcher#54]
exogui is currently stripping leading zeros from shell script parameters. This is causing many things, such as disk magazines, to fail launching.
![stripped0](https://github.com/user-attachments/assets/6be6b0c7-fdff-4bfc-aa7c-a796a815c075)

In the above example, it says `Launch Game "Big Blue Disk 056"`
`LaunchCommand` should also reflect this with `"056"`, and the final command should be `"/home/deck/eXoDOS/eXo/Magazines/Big\ Blue\ Disk.command 056"`

As this directly breaks entries in the eXoDOS Media Pack, it needs to be fixed before the eXoDOS 6.4 release.

**Comment by colin969** [comment]
Fixed by https://github.com/margorski/exodos-launcher/commit/c79dc3555cc72df4b1e0c583fe3d08cb040e601a
